# Game theory Assignment 1 Submitted by Aman Kanshotia(M21MA201)

# Q.1 Zero Sum Game

In [44]:
import numpy as np

def Dominance(payoff_matrix):

    dominated_rows = set()
    dominated_cols = set()

    num_rows, num_cols = payoff_matrix.shape

    # Check for dominated strategies for Row Player
    for i in range(num_rows):
        for j in range(num_rows):
            if i != j and i not in dominated_rows:
                if np.all(payoff_matrix[i] <= payoff_matrix[j]):
                    dominated_rows.add(i)

    # Check for dominated strategies for Column Player
    for i in range(num_cols):
        for j in range(num_cols):
            if i != j and i not in dominated_cols:
                if np.all(payoff_matrix[:, i] >= payoff_matrix[:, j]):
                    dominated_cols.add(i)

    return list(dominated_rows), list(dominated_cols)

def saddle_point(payoff_matrix):
    min_values = np.min(payoff_matrix, axis=1)
    max_values = np.max(payoff_matrix, axis=0)

    for i in range(payoff_matrix.shape[0]):
        for j in range(payoff_matrix.shape[1]):
            if payoff_matrix[i, j] == min_values[i] == max_values[j]:
                return payoff_matrix[i, j]  # Saddle point found
    return None

def fictitious_play(payoff_matrix, num_iterations=10000):
    # Check for dominated strategies
    dominated_rows, dominated_cols = Dominance(payoff_matrix)

    # Remove dominated strategies from the payoff matrix
    if dominated_rows or dominated_cols:
        payoff_matrix = np.delete(payoff_matrix, dominated_rows, axis=0)
        payoff_matrix = np.delete(payoff_matrix, dominated_cols, axis=1)

    # Check for saddle point
    saddle_value = saddle_point(payoff_matrix)
    if saddle_value is not None:
        return {"Saddle Point": saddle_value}

    num_rows, num_cols = payoff_matrix.shape

    p1_counts = np.ones(num_rows)
    p2_counts = np.ones(num_cols)

    # Iterate over the specified number of iterations
    for iteration in range(num_iterations):

        p1_strategy = p1_counts / np.sum(p1_counts)
        p2_strategy = p2_counts / np.sum(p2_counts)

        p1_best_response = np.argmax(np.dot(payoff_matrix, p2_strategy))

        p2_best_response = np.argmin(np.dot(payoff_matrix.T, p1_strategy))

        p1_counts[p1_best_response] += 1
        p2_counts[p2_best_response] += 1

    p1_strategy = p1_counts / np.sum(p1_counts)
    p2_strategy = p2_counts / np.sum(p2_counts)

    average_payoff = np.dot(p1_strategy, np.dot(payoff_matrix, p2_strategy))

    return {
        "Row Player Strategy": p1_strategy,
        "Column Player Strategy": p2_strategy,
        "Value of the Game": average_payoff
    }

In [45]:
# Example 1: Solve a zero-sum game

payoff_matrix = np.array([
    [0, 1, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0],
    [0, 1, 0, 1, 0, 0, 0],
    [0, 0, 1, 0, 1, 0, 0],
    [0, 0, 0, 1, 0, 1, 0],
    [0, 0, 0, 0, 1, 0, 1],
    [0, 0, 0, 0, 0, 1, 0],
])

print("The Given Payoff matrix:\n",payoff_matrix)

solution = fictitious_play(payoff_matrix)

# Outputs
print("--------------------------------------------------------------------------------------------")
if "Saddle Point" in solution:
    print("Saddle Point Value:", solution["Saddle Point"])
else:
    print("Row Player's Mixed Strategy(p):",
          [f"{prob:.2f}" for prob in solution["Row Player Strategy"]])
    print("Column Player's Mixed Strategy(q):",
          [f"{prob:.2f}" for prob in solution["Column Player Strategy"]])
    print("Value of the Game:", round(solution["Value of the Game"], 2))
print("--------------------------------------------------------------------------------------------")

The Given Payoff matrix:
 [[0 1 0 0 0 0 0]
 [1 0 1 0 0 0 0]
 [0 1 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 1 0 1 0]
 [0 0 0 0 1 0 1]
 [0 0 0 0 0 1 0]]
--------------------------------------------------------------------------------------------
Row Player's Mixed Strategy(p): ['0.24', '0.25', '0.00', '0.25', '0.25']
Column Player's Mixed Strategy(q): ['0.25', '0.25', '0.00', '0.25', '0.25']
Value of the Game: 0.25
--------------------------------------------------------------------------------------------


In [46]:
# Example 2: Solve a zero-sum game
payoff_matrix = np.array([[1, 2, 3, 4],
                          [4, 3, 2, 9],
                          [4, 3, 0, 1],
                          [0, 1, 4, 3]
                          ])

print("The Given Payoff matrix:\n", payoff_matrix)

solution = fictitious_play(payoff_matrix)

# Outputs
print("--------------------------------------------------------------------------------------------")
if "Saddle Point" in solution:
    print("Saddle Point Value:", solution["Saddle Point"])
else:
    print("Row Player's Mixed Strategy(p):",
          [f"{prob:.2f}" for prob in solution["Row Player Strategy"]])
    print("Column Player's Mixed Strategy(q):",
          [f"{prob:.2f}" for prob in solution["Column Player Strategy"]])
    print("Value of the Game:", round(solution["Value of the Game"], 2))
print("--------------------------------------------------------------------------------------------")

The Given Payoff matrix:
 [[1 2 3 4]
 [4 3 2 9]
 [4 3 0 1]
 [0 1 4 3]]
--------------------------------------------------------------------------------------------
Row Player's Mixed Strategy(p): ['0.00', '0.75', '0.25']
Column Player's Mixed Strategy(q): ['0.00', '0.51', '0.49', '0.00']
Value of the Game: 2.5
--------------------------------------------------------------------------------------------


##Q.2 Game matrix with Matrix Components

In [48]:
import numpy as np

def dominance(payoff_matrix):
    dominated_rows = set()
    dominated_cols = set()

    num_rows, num_cols = payoff_matrix.shape

    for i in range(num_rows):
        for j in range(num_rows):
            if i != j and i not in dominated_rows:
                if np.all(payoff_matrix[i] <= payoff_matrix[j]):
                    dominated_rows.add(i)

    for i in range(num_cols):
        for j in range(num_cols):
            if i != j and i not in dominated_cols:
                if np.all(payoff_matrix[:, i] >= payoff_matrix[:, j]):
                    dominated_cols.add(i)

    return list(dominated_rows), list(dominated_cols)

def saddle_point(payoff_matrix):
    min_values = np.min(payoff_matrix, axis=1)
    max_values = np.max(payoff_matrix, axis=0)

    for i in range(payoff_matrix.shape[0]):
        for j in range(payoff_matrix.shape[1]):
            if payoff_matrix[i, j] == min_values[i] == max_values[j]:
                return payoff_matrix[i, j]
    return None

def submatrix_solver(entry):
    if isinstance(entry, np.ndarray):
        # Call fictitious_play recursively for sub-matrices
        sub_solution = fictitious_play(entry)
        if "Value of the Game" in sub_solution:
            print("--------------------------------------------------------------------------------------------\n")
            print("Component matrix:")
            print(entry)
            print("Component matrix value:", round(sub_solution["Value of the Game"], 2))
            print("Component matrix row player strategy:", [f"{prob:.2f}" for prob in sub_solution["row player Strategy"]])
            print("Component matrix column player strategy:", [f"{prob:.2f}" for prob in sub_solution["column player Strategy"]])
            print("--------------------------------------------------------------------------------------------\n")
            return sub_solution["Value of the Game"]
        else:
            print("--------------------------------------------------------------------------------------------\n")
            print("Component matrix:")
            print(entry)
            print("Component matrix solved (saddle point found and value is):", sub_solution["Saddle Point"])
            print("--------------------------------------------------------------------------------------------\n")
            return sub_solution["Saddle Point"]
    return entry

def updated_payoff_matrix(payoff_matrix):
    resolved_matrix = np.copy(payoff_matrix)
    for i in range(payoff_matrix.shape[0]):
        for j in range(payoff_matrix.shape[1]):
            resolved_matrix[i, j] = submatrix_solver(payoff_matrix[i, j])
    return resolved_matrix

def fictitious_play(payoff_matrix, num_iterations=10000):
    # Resolve Component matrix entries first
    payoff_matrix = updated_payoff_matrix(payoff_matrix)

    # Check for dominated strategies
    dominated_rows, dominated_cols = dominance(payoff_matrix)

    # Remove dominated strategies from the payoff matrix
    if dominated_rows or dominated_cols:
        payoff_matrix = np.delete(payoff_matrix, dominated_rows, axis=0)
        payoff_matrix = np.delete(payoff_matrix, dominated_cols, axis=1)

    # Checking for saddle point
    saddle_value = saddle_point(payoff_matrix)
    if saddle_value is not None:
        return {"Saddle Point": saddle_value}

    num_rows, num_cols = payoff_matrix.shape

    # Initialize strategy counts for each player
    p1_counts = np.ones(num_rows)
    p2_counts = np.ones(num_cols)

    for iteration in range(num_iterations):
        p1_strategy = p1_counts / np.sum(p1_counts)
        p2_strategy = p2_counts / np.sum(p2_counts)

        p1_best_response = np.argmax(np.dot(payoff_matrix, p2_strategy))

        p2_best_response = np.argmin(np.dot(payoff_matrix.T, p1_strategy))

        # Updated strategy counts
        p1_counts[p1_best_response] += 1
        p2_counts[p2_best_response] += 1

    p1_strategy = p1_counts / np.sum(p1_counts)
    p2_strategy = p2_counts / np.sum(p2_counts)

    # Calculating average payoff for row player
    average_payoff = np.dot(p1_strategy, np.dot(payoff_matrix, p2_strategy))

    return {
        "row player Strategy": p1_strategy,
        "column player Strategy": p2_strategy,
        "Value of the Game": average_payoff
    }


In [49]:
# Example 3: Solve a zero-sum game with Component matrix entries
payoff_matrix = np.array([
    [np.array([[0, 3], [2, -1]]),4, np.array([[0, 1], [12, -1]]),5],
    [5,np.array([[0, 1], [4, 3]]),3,np.array([[1, 2], [5, -4]])]
], dtype=object)

print("The Given Payoff matrix:\n",payoff_matrix)

solution = fictitious_play(payoff_matrix)

# Outputs
print("--------------------------------------------------------------------------------------------\n")
if "Saddle Point" in solution:
    print("Saddle Point Value:", solution["Saddle Point"])
else:
    print("row player's Mixed Strategy(p):", [f"{prob:.2f}" for prob in solution["row player Strategy"]])
    print("column player's Mixed Strategy(q):", [f"{prob:.2f}" for prob in solution["column player Strategy"]])
    print("Value of the Game:", round(solution["Value of the Game"], 2))
print("--------------------------------------------------------------------------------------------\n")


The Given Payoff matrix:
 [[array([[ 0,  3],
         [ 2, -1]]) 4 array([[ 0,  1],
                             [12, -1]]) 5]
 [5 array([[0, 1],
           [4, 3]]) 3 array([[ 1,  2],
                             [ 5, -4]])]]
--------------------------------------------------------------------------------------------

Component matrix:
[[ 0  3]
 [ 2 -1]]
Component matrix value: 1.0
Component matrix row player strategy: ['0.51', '0.49']
Component matrix column player strategy: ['0.67', '0.33']
--------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------

Component matrix:
[[ 0  1]
 [12 -1]]
Component matrix value: 0.86
Component matrix row player strategy: ['0.92', '0.08']
Component matrix column player strategy: ['0.13', '0.87']
--------------------------------------------------------------------------------------------

----------------------------------------

In [50]:
# Example 4: Solve a zero-sum game with Component matrix entries
payoff_matrix = np.array([
    [np.array([[0, 1], [1, -1]]),4, np.array([[0, 1], [12, -1]]),np.array([[1, 4], [-4, 0]])],
    [5,np.array([[0, 1], [4, 3]]),np.array([[1, -4], [123, -5]]),np.array([[-1, 9], [-5, -4]])]
], dtype=object)

print("The Given Payoff matrix:\n",payoff_matrix)

solution = fictitious_play(payoff_matrix)

# Outputs
print("--------------------------------------------------------------------------------------------\n")
if "Saddle Point" in solution:
    print("Saddle Point Value:", solution["Saddle Point"])
else:
    print("row player's Mixed Strategy(p):", [f"{prob:.2f}" for prob in solution["row player Strategy"]])
    print("column player's Mixed Strategy(q):", [f"{prob:.2f}" for prob in solution["column player Strategy"]])
    print("Value of the Game:", round(solution["Value of the Game"], 2))
print("--------------------------------------------------------------------------------------------\n")


The Given Payoff matrix:
 [[array([[ 0,  1],
         [ 1, -1]]) 4 array([[ 0,  1],
                             [12, -1]]) array([[ 1,  4],
                                               [-4,  0]])]
 [5 array([[0, 1],
           [4, 3]]) array([[  1,  -4],
                           [123,  -5]]) array([[-1,  9],
                                               [-5, -4]])]]
--------------------------------------------------------------------------------------------

Component matrix:
[[ 0  1]
 [ 1 -1]]
Component matrix value: 0.33
Component matrix row player strategy: ['0.67', '0.33']
Component matrix column player strategy: ['0.66', '0.34']
--------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------

Component matrix:
[[ 0  1]
 [12 -1]]
Component matrix value: 0.86
Component matrix row player strategy: ['0.92', '0.08']
Component matrix column player strategy: ['

## Q.3 Recurssive games

In [51]:
import numpy as np

MAX_RECURSION_DEPTH = 5  ##Setting a limit to recursion depth to prevent infinite recursion

def dominance(payoff_matrix):
    dominated_rows = set()
    dominated_cols = set()

    num_rows, num_cols = payoff_matrix.shape

    for i in range(num_rows):
        for j in range(num_rows):
            if i != j and i not in dominated_rows:
                if np.all(payoff_matrix[i] <= payoff_matrix[j]):
                    dominated_rows.add(i)

    for i in range(num_cols):
        for j in range(num_cols):
            if i != j and i not in dominated_cols:
                if np.all(payoff_matrix[:, i] >= payoff_matrix[:, j]):
                    dominated_cols.add(i)

    return list(dominated_rows), list(dominated_cols)

def saddle_point(payoff_matrix):
    min_values = np.min(payoff_matrix, axis=1)
    max_values = np.max(payoff_matrix, axis=0)

    for i in range(payoff_matrix.shape[0]):
        for j in range(payoff_matrix.shape[1]):
            if payoff_matrix[i, j] == min_values[i] == max_values[j]:
                return payoff_matrix[i, j]
    return None

def solve_recursive_game(entry, original_matrix, depth=0):
    if isinstance(entry, (int, float)):
        return entry
    elif entry == "R":
        if depth > MAX_RECURSION_DEPTH:
            return 0
        sub_solution = fictitious_play(original_matrix, num_iterations=10000, depth=depth + 1)
        if "Value of the Game" in sub_solution:
            return sub_solution["Value of the Game"]
        elif "Saddle Point" in sub_solution:
            return sub_solution["Saddle Point"]
    return entry

def resolve_recursive_entries(payoff_matrix, original_matrix, depth=0):
    resolved_matrix = np.copy(payoff_matrix)
    for i in range(payoff_matrix.shape[0]):
        for j in range(payoff_matrix.shape[1]):
            resolved_matrix[i, j] = solve_recursive_game(payoff_matrix[i, j], original_matrix, depth)
    return resolved_matrix

def fictitious_play(payoff_matrix, num_iterations=100, depth=0):
    # Resolve recursive entries
    payoff_matrix = resolve_recursive_entries(payoff_matrix, payoff_matrix, depth)

    # Check for dominated strategies
    dominated_rows, dominated_cols = dominance(payoff_matrix)

    # Remove dominated strategies from the payoff matrix
    if dominated_rows or dominated_cols:
        payoff_matrix = np.delete(payoff_matrix, dominated_rows, axis=0)
        payoff_matrix = np.delete(payoff_matrix, dominated_cols, axis=1)

    # Checking for saddle point
    saddle_value = saddle_point(payoff_matrix)
    if saddle_value is not None:
        return {"Saddle Point": saddle_value}

    num_rows, num_cols = payoff_matrix.shape

    # Initialize strategy counts for each player
    p1_counts = np.ones(num_rows)
    p2_counts = np.ones(num_cols)

    # Iterate over the specified number of iterations
    for iteration in range(num_iterations):
        p1_strategy = p1_counts / np.sum(p1_counts)
        p2_strategy = p2_counts / np.sum(p2_counts)

        p1_best_response = np.argmax(np.dot(payoff_matrix, p2_strategy))
        p2_best_response = np.argmin(np.dot(payoff_matrix.T, p1_strategy))

        # Update strategy counts
        p1_counts[p1_best_response] += 1
        p2_counts[p2_best_response] += 1

    p1_strategy = p1_counts / np.sum(p1_counts)
    p2_strategy = p2_counts / np.sum(p2_counts)

    # Calculate the average payoff for row player
    average_payoff = np.dot(p1_strategy, np.dot(payoff_matrix, p2_strategy))

    return {
        "row player Strategy": p1_strategy,
        "column player Strategy": p2_strategy,
        "Value of the Game": average_payoff
    }



In [52]:
# Example 5: Solve a recursive zero-sum game where the original matrix itself is used recursively
payoff_matrix = np.array([
    ["R", 1, 0],
    [1, 0, "R"],
    [0, "R", 1]
], dtype=object)  # "R" refers to the original recursive matrix

print("The Given Payoff matrix:\n",payoff_matrix)

solution = fictitious_play(payoff_matrix)

# Final Outputs
print("--------------------------------------------------------------------------------------------")
if "Saddle Point" in solution:
    print("Saddle Point Value:", solution["Saddle Point"])
else:
    print("row player's Mixed Strategy:", [f"{prob:.2f}" for prob in solution["row player Strategy"]])
    print("column player's Mixed Strategy:", [f"{prob:.2f}" for prob in solution["column player Strategy"]])
    print("Value of the Game:", round(solution["Value of the Game"], 2))
print("--------------------------------------------------------------------------------------------")


The Given Payoff matrix:
 [['R' 1 0]
 [1 0 'R']
 [0 'R' 1]]
--------------------------------------------------------------------------------------------
row player's Mixed Strategy: ['0.28', '0.39', '0.33']
column player's Mixed Strategy: ['0.37', '0.31', '0.32']
Value of the Game: 0.5
--------------------------------------------------------------------------------------------


In [54]:
# Example 6: Solve a recursive zero-sum game where the original matrix itself is used recursively
payoff_matrix = np.array([
    ["R", 1],
    [1, "R"]
], dtype=object)  # "R" refers to the original recursive matrix

print("The Given Payoff matrix:\n",payoff_matrix)

solution = fictitious_play(payoff_matrix)

# Final Outputs
print("--------------------------------------------------------------------------------------------")
if "Saddle Point" in solution:
    print("Saddle Point Value:", solution["Saddle Point"])
else:
    print("row player's Mixed Strategy:", [f"{prob:.2f}" for prob in solution["row player Strategy"]])
    print("column player's Mixed Strategy:", [f"{prob:.2f}" for prob in solution["column player Strategy"]])
    print("Value of the Game:", round(solution["Value of the Game"], 2))
print("--------------------------------------------------------------------------------------------")


The Given Payoff matrix:
 [['R' 1]
 [1 'R']]
--------------------------------------------------------------------------------------------
row player's Mixed Strategy: ['0.52', '0.48']
column player's Mixed Strategy: ['0.55', '0.45']
Value of the Game: 0.99
--------------------------------------------------------------------------------------------
